# Example  .gitlab-ci.yml file
stages:
  - maventry
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidtry
  - androidbuild
  - androidtest

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - mvn package

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

# Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

#basically builds, then copies the jar to the /target folder, then stops existing service, and finally restarts it.

android-build: #this is another job
  image: gjandres/android-ci:latest      # this is a directive to DOCKER
  stage: androidtry
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Tarp/gradlew
  script:
    - cd Frontend/Tarp
    - ./gradlew assemble

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Tarp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/Tarp
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/Tarp/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/Tarp
    - ./gradlew test

